---
name: InfluxDB
version: dev
slug: influxdb
description: Scalable datastore for metrics, events, and real-time analytics
url: https://github.com/hassio-addons/addon-influxdb
codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 1337
ingress_stream: true
panel_icon: mdi:chart-areaspline
startup: services
homeassistant: 0.92.0b2
hassio_api: true
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
  - ssl
ports:
  80/tcp: null
  8181/tcp: 8181
ports_description:
  80/tcp: Web interface (Not required for Ingress)
  8181/tcp: InfluxDB 3 HTTP API
auth_api: true
options:
  auth: true
  edition: core
  license_email: ""
  license_file: ""
  license_type: home
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  default_database: homeassistant
  default_write_api: v1
  node_id: ha-node
  cluster_id: ha-cluster
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  auth: bool
  edition: list(core|enterprise)?
  license_email: str?
  license_file: str?
  license_type: list(home|trial|commercial)?
  ssl: bool
  certfile: str
  keyfile: str
  admin_token: str?
  default_database: str
  default_write_api: list(v1|v2)?
  node_id: str?
  cluster_id: str?
  leave_front_door_open: bool?
